const getById = (id) => {
    const el = document.getElementById(id);
    if (!el) {
        throw new Error("Missing element: " + id);
    }
    return el;
};
export const dom = {
    getById,
    elMode1: getById("mode1Config"),
    elMode2: getById("mode2Config"),
    elKeyInput: getById("keyInput"),
    elMinRootInput: getById("minRootInput"),
    elLoopTimesInput: getById("loopTimesInput"),
    elLoopForeverToggle: getById("loopForeverToggle"),
    elLoopShiftInput: getById("loopShiftInput"),
    elProgressionRows: getById("progressionRows"),
    elChordTemplate: getById("chordRowTemplate"),
    elMode2Rows: getById("mode2Rows"),
    elMode2Template: getById("mode2RowTemplate"),
    elSaveProgressionName: getById("saveProgressionName"),
    elSaveProgressionError: getById("saveProgressionError"),
    elSaveProgressionControls: getById("saveProgressionControls"),
    elProgressionList: getById("progressionList"),
    elVelocityRoot: getById("velocityRoot"),
    elVelocityFifth: getById("velocityFifth"),
    elVelocitySeventh: getById("velocitySeventh"),
    elVelocityThird: getById("velocityThird"),
    elVelocityRootValue: getById("velocityRootValue"),
    elVelocityFifthValue: getById("velocityFifthValue"),
    elVelocitySeventhValue: getById("velocitySeventhValue"),
    elVelocityThirdValue: getById("velocityThirdValue"),
    elNextChordKeyInput: getById("nextChordKeyInput"),
    elAutoAdvanceToggle: getById("autoAdvanceToggle"),
    elAutoAdvanceSeconds: getById("autoAdvanceSeconds"),
    elPlaybackModeToggle: getById("playbackModeToggle"),
    elAmbienceModeToggle: getById("ambienceModeToggle"),
    elMetronomeControls: getById("metronomeControls"),
    elBpmInput: getById("bpmInput"),
    elBpbInput: getById("bpbInput"),
    elDroneKeyLabel: getById("droneKeyLabel"),
    elDroneChordLabel: getById("droneChordLabel"),
    elDroneTonicLabel: getById("droneTonicLabel"),
    elDroneNextLabel: getById("droneNextLabel"),
    elDroneNextTonicLabel: getById("droneNextTonicLabel"),
    elDroneProgressLabel: getById("droneProgressLabel"),
    elDroneChordList: getById("droneChordList"),
    elDroneStatus: getById("droneStatus"),
    btnStartAudio: getById("btnStartAudio"),
    btnStartDrone: getById("btnStartDrone"),
    btnStopDrone: getById("btnStopDrone"),
    btnNextChord: getById("btnNextChord"),
    btnAddChord: getById("btnAddChord"),
    btnSaveProgression: getById("btnSaveProgression"),
    elExercisePanel: getById("exercisePanel"),
};
