const getById = (id) => {
    const el = document.getElementById(id);
    if (!el) {
        throw new Error("Missing element: " + id);
    }
    return el;
};
export const dom = {
    getById,
    elMode1: getById("mode1Config"),
    elMode2: getById("mode2Config"),
    elKeyInput: getById("keyInput"),
    elMinRootInput: getById("minRootInput"),
    elLoopTimesInput: getById("loopTimesInput"),
    elLoopShiftInput: getById("loopShiftInput"),
    elProgressionRows: getById("progressionRows"),
    elChordTemplate: getById("chordRowTemplate"),
    elMode2Rows: getById("mode2Rows"),
    elMode2Template: getById("mode2RowTemplate"),
    elSaveProgressionName: getById("saveProgressionName"),
    elSaveProgressionError: getById("saveProgressionError"),
    elSaveProgressionControls: getById("saveProgressionControls"),
    elVelocityRoot: getById("velocityRoot"),
    elVelocityFifth: getById("velocityFifth"),
    elVelocitySeventh: getById("velocitySeventh"),
    elVelocityThird: getById("velocityThird"),
    elVelocityLead: getById("velocityLead"),
    elVelocityRootValue: getById("velocityRootValue"),
    elVelocityFifthValue: getById("velocityFifthValue"),
    elVelocitySeventhValue: getById("velocitySeventhValue"),
    elVelocityThirdValue: getById("velocityThirdValue"),
    elVelocityLeadValue: getById("velocityLeadValue"),
    elKeyLabel: getById("keyLabel"),
    elChordLabel: getById("chordLabel"),
    elTonicLabel: getById("tonicLabel"),
    elQuestionLabel: getById("questionLabel"),
    elTimeLabel: getById("timeLabel"),
    elAttemptsLabel: getById("attemptsLabel"),
    elStatus: getById("status"),
    elAnswers: getById("answers"),
    elCompletionPanel: getById("completionPanel"),
    elCompletionStats: getById("completionStats"),
    elCompletionSummary: getById("completionSummary"),
    elRerunControls: getById("rerunControls"),
    elProgressionList: getById("progressionList"),
    btnSaveProgression: getById("btnSaveProgression"),
    elLiveQuestionPanel: getById("liveQuestionPanel"),
    elTestRecords: getById("testRecords"),
    elStatsRecords: getById("statsRecords"),
    elStatsGroupSelect: getById("statsGroupSelect"),
    elStatsOrderSelect: getById("statsOrderSelect"),
    elTestFilterSelect: getById("testFilterSelect"),
    elRecordsTabButtons: Array.from(document.querySelectorAll("[data-records-tab]")),
    elRecordsTabPanels: Array.from(document.querySelectorAll("[data-records-panel]")),
    btnStartAudio: getById("btnStartAudio"),
    btnStartTest: getById("btnStartTest"),
    btnStopTest: getById("btnStopTest"),
    btnReplay: getById("btnReplay"),
    btnAddChord: getById("btnAddChord"),
};
